//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToursApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tour
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tour()
        {
            this.HotelOfTour = new HashSet<HotelOfTour>();
            this.TypeOfTour = new HashSet<TypeOfTour>();
            this.Types = new HashSet<Type>();
        }
    
        public int id { get; set; }
        public int TicetCount { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public byte[] ImagePreviw { get; set; }
        public decimal Price { get; set; }
        public bool IsActual { get; set; }
        public string ActualText
        {
            get
            {
                return (IsActual) ? "Актуален" : "Завершен";
            }
        }

        public virtual ICollection<Type> Types { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HotelOfTour> HotelOfTour { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TypeOfTour> TypeOfTour { get; set; }
    }
}
